kind: pipeline
name: sonar-test


steps:
- name: test-branch
  image: bcyangguang/tmp-drone-test
  settings:
    sonar_host:  http://43.130.201.130:9000/
    sonar_token: 23a5488d63bb30cd1e2a6d769efa26cf31e9373c
    projectkey: sonarpr_test_t1
    branchAnalysis: true
  when:
    branch:
      - main
      - master
      - feature/*
    event:
      exclude:
      - pull_request
